### ISSUE TITLE
Tristate in Kconfiglib

### ISSUE THREAD

**Issue by ulfalizer** [sonydevworld/spresense-vscode-ide#3]
Hello,

Re.,

https://github.com/sonydevworld/spresense-vscode-ide/blob/b2a2e17c3f5bb5de16f3e8d1eb6595d873003498/resources/main.js#L852

Kconfiglib supports `tristate` symbols (which can take `m` values). The `MODULES` symbol needs to be set to `y` though, or `tristate` symbols get treated as `bool` symbols. It works the same as in the C tools.

See the docstring for `Symbol.orig_type` as well. It always gives the original type. `Symbol.type` applies `MODULES` magic.

Cheers,
Ulf

**Comment by SPRESENSE** [comment]
Thank you for advice, and sorry too late replying.

We have had misunderstood.
"tristate is unsupported because SDK don't use it for now" is correct.

We will fix it in the future.

Best Regards,
Spresense developer team

**Comment by SPRESENSE** [comment]
Spresense VSCode IDE supports `Tristate` symbol from v1.2.0.

Best Regards,
Spresense developer team
